version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  bot:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
    volumes:
      - .:/app
    command: ["cron", "-f"]
    environment:
      - GIT_REPO_URL=https://github.com/QGJ37/filsgood_bot.git
      - GIT_BRANCH=main
