services:
  bot:
    build:
      context: .  # Le contexte local au dépôt Git
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
    # Volume supprimé pour éviter les conflits avec Portainer
    command: ["sh", "-c", "until curl -s selenium:4444/wd/hub/status | grep -q '200'; do echo 'En attente de Selenium...'; sleep 3; done; echo 'Selenium prêt, lancement du bot'; cron -f"]
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
