version: '3'

services:
  bot:
    build: .
    volumes:
      - .:/mnt/nvme-data/AppData/filsgood_bot  # Monte le répertoire local dans le conteneur
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
