version: "3.8"

services:
  selenium:
    container_name: filsgood_bot-selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - filsgood_bot_network

  bot:
    container_name: filsgood_bot
    image: python:3.9-slim
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=filsgood_bot-selenium
    volumes:
      - /AppData/filsgood_bot:/app
    command: >
      sh -c "
        echo 'Mise à jour des paquets...' &&
        apt-get update &&
        apt-get install -y curl git python3-pip &&
        pip install selenium &&
        git config --global core.fileMode false &&
        chmod -R 777 /app &&
        git clone https://github.com/QGJ37/filsgood_bot.git /app &&
        echo 'Vérification de la disponibilité de Selenium...' &&
        until curl -s http://filsgood_bot-selenium:4444/wd/hub/status | grep -q '\"ready\": true'; do
          echo 'En attente de Selenium...';
          sleep 5;
        done &&
        echo 'Selenium prêt. Lancement en boucle...' &&
        while true; do
          echo 'Exécution du bot...';
          python3 /app/bot.py;
          sleep 600;
        done"

    restart: unless-stopped
    networks:
      - filsgood_bot_network

networks:
  filsgood_bot_network:
    driver: bridge
