version: "3.8"

services:
  selenium:
    container_name: filsgood_bot-selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - filsgood_bot_network

  bot:
    container_name: filsgood_bot
    image: python:3.9-slim
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=filsgood_bot-selenium
    volumes:
      - /mnt/nvme-data/AppData/filsgood_bot:/app
    command: ["sh", "-c", "apt-get update && apt-get install -y curl cron git && git config --global core.fileMode false && chmod -R 777 /app && git clone https://github.com/QGJ37/filsgood_bot.git /app && cp /app/cronfile /etc/cron.d/filsgood_bot && chmod 0644 /etc/cron.d/filsgood_bot && cron && touch /var/log/cron_custom.log && tail -f /var/log/cron_custom.log"]
    restart: unless-stopped
    networks:
      - filsgood_bot_network

networks:
  filsgood_bot_network:
    driver: bridge
