version: '3'

services:
  bot:
    build:
      context: .  # Chemin vers ton répertoire local
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      
    volumes:
      - /mnt/nvme-data/AppData/filsgood_bot:/app  # Assure-toi de faire le lien entre ton dossier local et le conteneur
    command: ["cron", "-f"]
    restart: unless-stopped
 
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
