version: "3.8"

services:
  selenium:
    container_name: filsgood_bot-selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - filsgood_bot_network

  bot:
    container_name: filsgood_bot
    image: python:3.11-slim
    user: root
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=filsgood_bot-selenium
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./filsgood_bot:/app
    working_dir: /app
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y curl git python3-venv python3-pip &&
        if [ ! -d /app/venv ]; then
          python3 -m venv /app/venv;
        fi &&
        . /app/venv/bin/activate &&
        pip install --upgrade pip &&
        pip install selenium requests &&
        until curl -s http://filsgood_bot-selenium:4444/wd/hub/status | grep -q '\"ready\": true'; do
          echo 'En attente de Selenium...';
          sleep 5;
        done &&
        python3 /app/scheduler.py
      "
    restart: unless-stopped
    networks:
      - filsgood_bot_network

networks:
  filsgood_bot_network:
    driver: bridge
