version: "3.8"

services:
  selenium:
    container_name: filsgood_bot-selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - filsgood_bot_network

  bot:
    container_name: filsgood_bot
    image: python:3.9-slim
    user: root
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=filsgood_bot-selenium
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
    volumes:
      - /AppData/filsgood_bot:/app
    command: >
      sh -c "
        echo 'Mise à jour des paquets...' &&
        apt-get update &&
        apt-get install -y curl git python3-venv python3-pip &&
        if [ ! -d /app/venv ]; then
          echo 'Création de l''environnement virtuel...' &&
          python3 -m venv /app/venv;
        else
          echo 'Environnement virtuel déjà existant...';
        fi &&
        echo 'Activation de l''environnement virtuel...' &&
        . /app/venv/bin/activate &&
        pip install --upgrade pip &&
        pip install --no-cache-dir selenium requests python-telegram-bot==13.15 &&
        git config --global core.fileMode false &&
        chmod -R 777 /app &&
        echo 'Suppression du contenu du dossier /app sauf /app/venv...' &&
        find /app -mindepth 1 ! -path '/app/venv*' -delete &&
        echo 'Clonage du dépôt Git...' &&
        git clone https://github.com/QGJ37/filsgood_bot.git /app/bot_code &&
        mv /app/bot_code/* /app/ &&
        rm -rf /app/bot_code &&
        echo 'Vérification de la disponibilité de Selenium...' &&
        until curl -s http://filsgood_bot-selenium:4444/wd/hub/status | grep -q '\"ready\": true'; do
          echo 'En attente de Selenium...';
          sleep 5;
        done &&
        echo 'Selenium prêt. Lancement du planificateur...' &&
        python3 /app/scheduler.py"
    restart: unless-stopped
    networks:
      - filsgood_bot_network

networks:
  filsgood_bot_network:
    driver: bridge
