version: "3.8"
services:
  bot:
    container_name: filsgood_bot
    image: python:3.9-slim
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=filsgood_bot-selenium  # Change l'hôte pour le nom du conteneur Selenium
    volumes:
      - /mnt/nvme-data/AppData/filsgood_bot:/app  # Assure-toi que le dossier est bien monté
    command: ["sh", "-c", "apt-get update && apt-get install -y curl && until curl -s http://filsgood_bot-selenium:4444/wd/hub/status | grep -q '200'; do echo 'En attente de Selenium...'; sleep 3; done; echo 'Selenium prêt, lancement du bot'; cron -f"]
    restart: unless-stopped
    network_mode: host  # Essaye avec ce mode si nécessaire
    networks:
      - filsgood_bot_network  # Réseau commun avec Selenium

  selenium:
    container_name: filsgood_bot-selenium
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - filsgood_bot_network  # Réseau commun avec le bot

networks:
  filsgood_bot_network:
    driver: bridge  # Utilisation du driver bridge
